### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by akaihola**

### CODE REVIEW

**Comment by mfonsen** [comment]
Big thanks for the PR!

Does this drop Python 2.7 compatibility?

I get the following error when testing on a Mac + Python 2.7.11: 

```
Traceback (most recent call last):
  File "statementparser.py", line 157, in <module>
    transactionsOsuuspankki = filereader(args.input,'csv',osuuspankki.transactionslookup)
  File "statementparser.py", line 98, in filereader
    transactions.extend(handlermethod(f,path))
  File "/Users/mika/projects/parsestatements/osuuspankki.py", line 207, in transactionslookup
    print('*** Reading file: {}'.format(path))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 53: ordinal not in range(128)
```

This points to: https://github.com/akaihola/parsestatements/blob/b828def5a72ae0479906fe0d18f22a2ca451302b/osuuspankki.py#L207

Planning to try this with Python 3 later.

**Comment by akaihola** [comment]
My purpose was to keep Python 2.7 compatibility. Most probably my test files didn't hit the code path you did. I'll try to fix that error.

**Comment by mfonsen** [comment]
It would seem like this is related to `from __future__ import unicode_literals` statement. http://python-future.org/unicode_literals.html#drawbacks seems to describe those errors that I'm bumping into.

Some background: If I comment out all print commands that cause this problem, the next error I get to is `TypeError: "delimiter" must be string, not unicode`. This lead me to http://stackoverflow.com/questions/5625412/python-csv-module-error

Perhaps it's not trivial to make this work on both Python 2.7 and 3.

**Comment by akaihola** [comment]
Closing the pull request to a dead project.

**Comment by Thaodan** [comment]
Did you found a replacement for this kind of program?

**Comment by akaihola** [comment]
> Did you found a replacement for this kind of program?

No, but now with help from [Aider](https://aider.chat/) and [Claude 3.5 Sonnet](https://www.anthropic.com/news/claude-3-5-sonnet) I could tackle the challenge must faster myself.

**Pull request closed without merging**
